# Generated by Django 5.2.10 on 2026-02-14 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receptionist',
            name='receptionist_email',
            field=models.EmailField(max_length=20),
        ),
    ]
