# Generated by Django 5.2.10 on 2026-02-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=20)),
                ('doctor_speciality', models.CharField(max_length=20)),
                ('doctor_fee', models.IntegerField()),
                ('doctor_slots', models.IntegerField()),
                ('doctor_otp', models.CharField(max_length=10)),
                ('doctor_number', models.CharField(max_length=20)),
                ('doctor_email', models.EmailField(max_length=20)),
                ('doctor_password', models.CharField(max_length=20)),
            ],
        ),
    ]
