# Generated by Django 5.2.10 on 2026-02-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointments",
            name="patient_age",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
