# Generated by Django 5.2.10 on 2026-02-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=20)),
                ('patient_age', models.IntegerField()),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_number', models.CharField(max_length=20)),
                ('appointment_data', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('doctor', models.CharField(max_length=20)),
                ('reason', models.TextField()),
            ],
        ),
    ]
