# Generated by Django 5.2.10 on 2026-02-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_appointments"),
    ]

    operations = [
        migrations.CreateModel(
            name="pharmacist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pharmacist_name", models.CharField(max_length=20)),
                ("pharmacist_number", models.CharField(max_length=20)),
                ("pharmacist_email", models.EmailField(max_length=20)),
                ("pharmacist_otp", models.CharField(max_length=10)),
                ("pharmacist_password", models.CharField(max_length=10)),
            ],
        ),
    ]
