# Generated by Django 5.2.10 on 2026-02-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescriptionorder",
            name="patient_email",
        ),
        migrations.AddField(
            model_name="prescriptionorder",
            name="patient_id",
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
