# Generated by Django 5.2.10 on 2026-02-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0002_remove_prescriptionorder_patient_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prescriptionorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Accepted", "Accepted"),
                    ("Completed", "Completed"),
                    ("Rejected", "Rejected"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
