# Generated by Django 5.2.10 on 2026-02-16 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medicine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("manufacturer", models.CharField(max_length=200)),
                ("stock", models.IntegerField()),
                ("price", models.FloatField()),
                ("expiry_date", models.DateField()),
            ],
        ),
    ]
