# Generated by Django 5.2.10 on 2026-02-17 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0002_medicine_created_at_medicine_low_stock_threshold_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="prescription",
            name="pharmacist",
        ),
        migrations.RemoveField(
            model_name="prescriptionitem",
            name="prescription",
        ),
        migrations.RemoveField(
            model_name="prescriptionitem",
            name="medicine",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="low_stock_threshold",
        ),
        migrations.RemoveField(
            model_name="medicine",
            name="updated_at",
        ),
        migrations.DeleteModel(
            name="InventoryAlert",
        ),
        migrations.DeleteModel(
            name="Prescription",
        ),
        migrations.DeleteModel(
            name="PrescriptionItem",
        ),
    ]
